import type { Flavour } from "@wow-locker/shared";

/** Static talent trees (generated by scripts/talents.ts from the game data). */
export type TalentDef = { id: number; tier: number; col: number; max: number; name: string; icon: string | null; req: number | null };
export type TreeDef = { name: string; order: number; icon: string | null; talents: TalentDef[] };
export type ClassTrees = Record<string, TreeDef[]>;

/** Only the tree-based flavours have generated data (MoP uses talent rows). */
export function hasTalentTrees(flavour: Flavour): flavour is "classic1x" | "classicann" {
  return flavour === "classic1x" || flavour === "classicann";
}

/** Loaded on demand (code-split per flavour): only the character page needs it. */
export async function loadTalentTrees(flavour: "classic1x" | "classicann"): Promise<ClassTrees> {
  const mod = flavour === "classic1x" ? await import("@/data/talents/classic1x.json") : await import("@/data/talents/classicann.json");
  return mod.default as ClassTrees;
}

export const iconUrl = (flavour: Flavour, region: string, icon: string | null) =>
  icon ? `https://render.worldofwarcraft.com/${flavour}-${region}/icons/56/${icon}.jpg` : null;
